FROM php:7.2-fpm-alpine

RUN cp "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

RUN apk update && \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS && \
    pecl install -o -f redis && \
    rm -rf /tmp/pear && \
    docker-php-ext-enable redis && \
    apk del .build-deps && \
    rm -rf /tmp/* /var/cache/apk/*

ADD . /var/www/app

ENV NAME World

EXPOSE 9000

CMD php-fpm
