version: "3"
services:
  nginx:
    image: ittmann/getstartedphp:nginx-part3b
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - webnet
    links:
      - php
  php-fpm:
    image: ittmann/getstartedphp:php-fpm-part3b
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
    environment:
      NAME: World
networks:
  webnet:
